---
name: influx-grafana
director_uuid: d1ac7054-ab09-4845-afff-f6ce1f770f65

releases:
- name: grafana
  version: 9
- name: influxdb
  version: 4
- name: routing
  version: 0.144.0

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: influxdb
  azs: [us-east1-b]
  instances: 1
  stemcell: trusty
  networks:
  - name: manual-bosh
    default:
    - dns
    - gateway
    static_ips:
    - 10.0.0.202
  persistent_disk_type: '20480'
  vm_type: medium.disk
  vm_extensions:
  # replace with a VM extension from your BOSH Director's cloud config that will attach
  # this instance group to your ELB
  - vm-extension-pcf
  templates:
  - name: influxdb
    release: influxdb
  - name: grafana
    release: grafana
  - name: route_registrar
    release: routing
  update:
    serial: true
  properties:
    influxdb:
      database: GeodeJmx
    grafana:
      admin_password: p1v0tal
      admin_username: admin
      auth:
        anonymous:
          enabled: true
          organization_role: Admin
      datasources:
      - name: influxdb
        url: http://localhost:8086
        type: influxdb
        user: root
        password: root
        database: GeodeJmx
      session:
        cookie_name: g-cookie
        cookie_secure: false
        session_life_time: 720
    route_registrar:
      routes:
      - name: grafana
        port: 3000
        registration_interval: 20s
        uris:
        - grafana.apps.cloud.zwickey.net
      - name: influxdb-ui
        port: 8083
        registration_interval: 20s
        uris:
        - influxdb-ui.apps.cloud.zwickey.net
      - name: influxdb
        port: 8086
        registration_interval: 20s
        uris:
        - influxdb.apps.cloud.zwickey.net
    nats:
      machines:
      - 10.0.0.16
      password: qZn-CxTGaCNwHVSXPhM0XNQ8Tw_AgNoS
      port: 4222
      user: nats

update:
  canaries: 1
  canary_watch_time: 1000-30000
  max_in_flight: 3
  serial: false
  update_watch_time: 1000-30000
