resources:
- name: assets
  type: git
  source:
    uri: https://github.com/azwickey-pivotal/gcp-quiesce
    branch: master

jobs:
- name: status
  serial: true
  public: true
  plan:
  - get: assets
    trigger: false
  - task: bosh-cacert
    file:  assets/ci/tasks/cacert.yml
    params:
      BOSH_URL: {{bosh-url}}
      BOSH_CACERT: {{bosh-cacert}}
      BOSH_CLIENT: {{bosh-client}}
      BOSH_CLIENT_SECRET: {{bosh-secret}}
  - task: bosh-vms
    file:  assets/ci/tasks/vms.yml
    params:
      BOSH_URL: {{bosh-url}}
      BOSH_CLIENT: {{bosh-client}}
      BOSH_CLIENT_SECRET: {{bosh-secret}}
- name: pre-start-check
  serial: true
  public: true
  plan:
  - get: assets
    trigger: false
  - task: bosh-cacert
    file:  assets/ci/tasks/cacert.yml
    params:
      BOSH_URL: {{bosh-url}}
      BOSH_CACERT: {{bosh-cacert}}
      BOSH_CLIENT: {{bosh-client}}
      BOSH_CLIENT_SECRET: {{bosh-secret}}
  - task: bosh-vms
    file:  assets/ci/tasks/vms.yml
    params:
      BOSH_URL: {{bosh-url}}
      BOSH_CLIENT: {{bosh-client}}
      BOSH_CLIENT_SECRET: {{bosh-secret}}
- name: start
  serial: true
  public: true
  plan:
  - get: assets
    trigger: true
    passed:
      - pre-start-check
  - task: bosh-cacert
    file:  assets/ci/tasks/cacert.yml
    params:
      BOSH_URL: {{bosh-url}}
      BOSH_CACERT: {{bosh-cacert}}
      BOSH_CLIENT: {{bosh-client}}
      BOSH_CLIENT_SECRET: {{bosh-secret}}
  - task: start-deployments
    file:  assets/ci/tasks/start.yml
    params:
      BOSH_URL: {{bosh-url}}
      BOSH_CLIENT: {{bosh-client}}
      BOSH_CLIENT_SECRET: {{bosh-secret}}
      DEPLOYMENTS: {{deployments}}
- name: check-env
  serial: true
  public: true
  plan:
  - get: assets
    trigger: true
    passed:
    - start
  - task: bosh-cacert
    file:  assets/ci/tasks/cacert.yml
    params:
      BOSH_URL: {{bosh-url}}
      BOSH_CACERT: {{bosh-cacert}}
      BOSH_CLIENT: {{bosh-client}}
      BOSH_CLIENT_SECRET: {{bosh-secret}}
  - task: bosh-vms
    file:  assets/ci/tasks/vms.yml
    params:
      BOSH_URL: {{bosh-url}}
      BOSH_CLIENT: {{bosh-client}}
      BOSH_CLIENT_SECRET: {{bosh-secret}}
  - task: bosh-vms-check
    file:  assets/ci/tasks/failing-vms.yml
    params:
      BOSH_URL: {{bosh-url}}
      BOSH_CLIENT: {{bosh-client}}
      BOSH_CLIENT_SECRET: {{bosh-secret}}
- name: pre-stop-check
  serial: true
  public: true
  plan:
  - get: assets
    trigger: false
  - task: bosh-cacert
    file:  assets/ci/tasks/cacert.yml
    params:
      BOSH_URL: {{bosh-url}}
      BOSH_CACERT: {{bosh-cacert}}
      BOSH_CLIENT: {{bosh-client}}
      BOSH_CLIENT_SECRET: {{bosh-secret}}
  - task: bosh-vms
    file:  assets/ci/tasks/vms.yml
    params:
      BOSH_URL: {{bosh-url}}
      BOSH_CLIENT: {{bosh-client}}
      BOSH_CLIENT_SECRET: {{bosh-secret}}
- name: stop
  serial: true
  public: true
  plan:
  - get: assets
    passed:
      - pre-stop-check
    trigger: true
  - task: bosh-cacert
    file:  assets/ci/tasks/cacert.yml
    params:
      BOSH_URL: {{bosh-url}}
      BOSH_CACERT: {{bosh-cacert}}
      BOSH_CLIENT: {{bosh-client}}
      BOSH_CLIENT_SECRET: {{bosh-secret}}
  - task: stop
    file:  assets/ci/tasks/stop.yml
    params:
      BOSH_URL: {{bosh-url}}
      BOSH_CLIENT: {{bosh-client}}
      BOSH_CLIENT_SECRET: {{bosh-secret}}
      DEPLOYMENTS: {{deployments}}
- name: check-running
  serial: true
  public: true
  plan:
  - get: assets
    trigger: true
    passed:
      - stop
  - task: bosh-cacert
    file:  assets/ci/tasks/cacert.yml
    params:
      BOSH_URL: {{bosh-url}}
      BOSH_CACERT: {{bosh-cacert}}
      BOSH_CLIENT: {{bosh-client}}
      BOSH_CLIENT_SECRET: {{bosh-secret}}
  - task: bosh-vms-check
    file:  assets/ci/tasks/running-vms.yml
    params:
      BOSH_URL: {{bosh-url}}
      BOSH_CLIENT: {{bosh-client}}
      BOSH_CLIENT_SECRET: {{bosh-secret}}
