

resources:
- name: assets
  type: git
  source:
    uri: git@github.com:Pivotal-Field-Engineering/gcp-quiesce.git
    branch: master
    private_key: {{github-key}}

jobs:
- name: quiesce
  serial: true
  public: true
  plan:
  - get: assets
    trigger: false
  - task: bosh-cacert
    file:  assets/ci/tasks/cacert.yml
    params:
      BOSH_URL: {{bosh-url}}
      BOSH_CACERT: {{bosh-cacert}}
      BOSH_CLIENT: {{bosh-client}}
      BOSH_CLIENT_SECRET: {{bosh-secret}}
  - task: bosh-vms
    file:  assets/ci/tasks/vms.yml
    params:
      BOSH_URL: {{bosh-url}}
      BOSH_CLIENT: {{bosh-client}}
      BOSH_CLIENT_SECRET: {{bosh-secret}}

- name: check
  serial: true
  public: true
  plan:
  - get: assets
    trigger: false
  - task: bosh-cacert
    file:  assets/ci/tasks/cacert.yml
    params:
      BOSH_URL: {{bosh-url}}
      BOSH_CACERT: {{bosh-cacert}}
      BOSH_CLIENT: {{bosh-client}}
      BOSH_CLIENT_SECRET: {{bosh-secret}}
  - task: bosh-vms-check
    file:  assets/ci/tasks/failing-vms.yml
    params:
      BOSH_URL: {{bosh-url}}
      BOSH_CLIENT: {{bosh-client}}
      BOSH_CLIENT_SECRET: {{bosh-secret}}

- name: pre-startup
  serial: true
  public: true
  plan:
  - get: assets
    trigger: false
  - task: bosh-cacert
    file:  assets/ci/tasks/cacert.yml
    params:
      BOSH_URL: {{bosh-url}}
      BOSH_CACERT: {{bosh-cacert}}
      BOSH_CLIENT: {{bosh-client}}
      BOSH_CLIENT_SECRET: {{bosh-secret}}
  - task: bosh-vms
    file:  assets/ci/tasks/vms.yml
    params:
      BOSH_URL: {{bosh-url}}
      BOSH_CLIENT: {{bosh-client}}
      BOSH_CLIENT_SECRET: {{bosh-secret}}
  - task: start-cf
    file:  assets/ci/tasks/start.yml
    params:
      BOSH_URL: {{bosh-url}}
      BOSH_CLIENT: {{bosh-client}}
      BOSH_CLIENT_SECRET: {{bosh-secret}}
      DEPLOYMENT_FILE: cf.yml
      DEPLOYMENT_NAME: cf-ddf5ae89e698bab6df31
  - task: bosh-vms-check
    file:  assets/ci/tasks/failing-vms.yml
    params:
      BOSH_URL: {{bosh-url}}
      BOSH_CLIENT: {{bosh-client}}
      BOSH_CLIENT_SECRET: {{bosh-secret}}
- name: startup-cf
  serial: true
  public: true
  plan:
  - get: assets
    passed:
      - pre-startup
    trigger: true
  - task: bosh-cacert
    file:  assets/ci/tasks/cacert.yml
    params:
      BOSH_URL: {{bosh-url}}
      BOSH_CACERT: {{bosh-cacert}}
      BOSH_CLIENT: {{bosh-client}}
      BOSH_CLIENT_SECRET: {{bosh-secret}}
  - task: start-cf
    file:  assets/ci/tasks/start.yml
    params:
      BOSH_URL: {{bosh-url}}
      BOSH_CLIENT: {{bosh-client}}
      BOSH_CLIENT_SECRET: {{bosh-secret}}
      DEPLOYMENT_FILE: cf.yml
      DEPLOYMENT_NAME: cf-ddf5ae89e698bab6df31
- name: check-env
  serial: true
  public: true
  plan:
  - get: assets
    passed:
      - startup-cf
  - task: bosh-cacert
    file:  assets/ci/tasks/cacert.yml
    params:
      BOSH_URL: {{bosh-url}}
      BOSH_CACERT: {{bosh-cacert}}
      BOSH_CLIENT: {{bosh-client}}
      BOSH_CLIENT_SECRET: {{bosh-secret}}
  - task: bosh-vms
    file:  assets/ci/tasks/vms.yml
    params:
      BOSH_URL: {{bosh-url}}
      BOSH_CLIENT: {{bosh-client}}
      BOSH_CLIENT_SECRET: {{bosh-secret}}
  - task: bosh-vms-check
    file:  assets/ci/tasks/failing-vms.yml
    params:
      BOSH_URL: {{bosh-url}}
      BOSH_CLIENT: {{bosh-client}}
      BOSH_CLIENT_SECRET: {{bosh-secret}}
